---
- name: Install dependencies
  dnf:
    name:
      - python
      - pip
      - python3-devel
      - python3-ipython
      - texlive
      - texlive-latex
      - texlive-type1cm
      - texlive-dvipng
      - gfortran
      - redis
    state: latest
  register: dnf

- name: Run texhash
  shell: texhash
  when: dnf.changed

- name: Install python deps
  pip:
    name:
      - wheel
      - jinja2
      - email-validator
      - rq
      - cerberus
      - pyyaml

- name: Check install_from variable
  assert:
    that:
      - install_from is in ['pypi','testpypi','source']

- name: Install StarFit
  import_tasks: from_{{ install_from }}.yml

- name: Run code to generate matplotlib and tex caches
  shell:
    cmd: sudo -u apache MPLCONFIGDIR={{ mplconfigdir }} python -c "import starfit; starfit.Single('HE1327-2326.dat').plot()"
