---
- name: Install dependencies
  dnf:
    name:
      - python
      - pip
      - python3-devel
      - python3-ipython
      - texlive
      - texlive-latex
      - texlive-type1cm
      - gfortran
    state: latest
  register: dnf

- name: Run texhash
  shell: texhash
  when: dnf.changed

- name: Install python deps
  pip:
    name:
      - wheel
      - jinja2
      - email-validator
      - rq

- name: Install StarFit
  pip:
    name: starfit
    extra_args: -U -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/

- name: Add html content
  copy:
    src: html
    dest: /var/www/
    mode: preserve

- name: Create mount point for data
  file:
    path: /var/www/html/data
    state: directory
    mode: "0755"

- name: Ensure starfit data is mounted and served
  mount:
    src: LABEL=starfit-data
    path: /var/www/html/data
    fstype: ext4
    opts: defaults
    dump: 0
    passno: 2
    state: mounted

- name: Run code to generate matplotlib and tex caches
  shell:
    cmd: sudo -u apache MPLCONFIGDIR={{ mplconfigdir }} python -c "import starfit; starfit.Single('HE1327-2326.dat').plot()"
