---
- name: Install dependencies
  dnf:
    name:
      - python
      - python3-devel
      - pip
      - python3-wheel
      - gfortran
    state: latest

- name: Install StarFit
  shell: pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ starfit

- name: Add html content
  copy:
    src: html
    dest: /var/www/
    mode: preserve

- name: Ensure starfit data is mounted and served
  mount:
    src: LABEL=starfit-data
    path: /var/www/html/data
    fstype: ext4
    opts: defaults
    dump: 0
    passno: 2
    state: remounted
