---
- name: Install RQ Monitor
  pip:
    name: rqmonitor

- name: Create RQ Monitor service
  copy:
    src: rqmonitor.service
    dest: /etc/systemd/system/rqmonitor.service
    owner: root
    group: root
    mode: 0600
  register: rqmonitor

- name: (re)start rqmonitor service
  systemd:
    state: "{{ 'restarted' if rqmonitor.changed else 'started' }}"
    name: rqmonitor
    enabled: true
