---
- name: Install the latest version of Apache
  dnf:
    name: httpd
    state: latest

- name: Configure domain name
  copy:
    dest: /etc/httpd/conf.d/{{ domain }}.conf
    content: |
      <VirtualHost *:80>
          ServerName {{ domain }}
          SetEnv MPLCONFIGDIR /usr/share/httpd/mplconfig.d
      </VirtualHost>

      <VirtualHost *:443>
          ServerName {{ domain }}
          SetEnv MPLCONFIGDIR /usr/share/httpd/mplconfig.d
      </VirtualHost>

      # Python CGI
      <Directory /var/www/html/py>
          Options ExecCGI
          SetHandler cgi-script
      </Directory>

    mode: "0644"

- name: Make sure Apache is running
  systemd:
    state: restarted
    name: httpd

- name: Create mplconfigdir
  file:
    path: /usr/share/httpd/mplconfig.d
    state: directory
    owner: apache
    group: apache
    mode: "0755"
