---
- name: Install the latest version of Apache
  dnf:
    name: httpd
    state: latest

- name: Set ServerName in apache config
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerName "
    insertafter: ^#ServerName
    line: ServerName localhost

- name: Create VirtualHosts in apache config
  blockinfile:
    dest: /etc/httpd/conf.d/{{ domain }}.conf
    create: true
    block: |
      SetEnv MPLCONFIGDIR {{ mplconfigdir }}

      <VirtualHost *:80>
          ServerName {{ domain }}
      </VirtualHost>

      <VirtualHost *:443>
          ServerName {{ domain }}
      </VirtualHost>

      # Python CGI
      <Directory /var/www/html/py>
          Options ExecCGI
          SetHandler cgi-script
      </Directory>
    mode: "0644"
  register: apacheconf

- name: (re)start apache
  systemd:
    state: "{{ 'restarted' if apacheconf.changed else 'started' }}"
    name: httpd

- name: Create custom "mplconfigdir"
  file:
    path: "{{ mplconfigdir }}"
    state: directory
    owner: apache
    group: apache
    mode: "0755"
