---
- name: Install the latest version of Apache
  dnf:
    name: httpd
    state: latest

- name: Add apache configuration
  blockinfile:
    dest: /etc/httpd/conf.d/{{ domain }}.conf
    create: true
    block: |
      <VirtualHost *:80>
          ServerName {{ domain }}
          SetEnv MPLCONFIGDIR {{ mplconfigdir }}
      </VirtualHost>

      <VirtualHost *:443>
          ServerName {{ domain }}
          SetEnv MPLCONFIGDIR {{ mplconfigdir }}
      </VirtualHost>

      # Python CGI
      <Directory /var/www/html/py>
          Options ExecCGI
          SetHandler cgi-script
      </Directory>
    mode: "0644"

- name: Restart Apache
  systemd:
    state: restarted
    name: httpd

- name: Create mplconfigdir
  file:
    path: "{{ mplconfigdir }}"
    state: directory
    owner: apache
    group: apache
    mode: "0755"
