---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      # - id: no-commit-to-branch
      #   args: [--branch, master]
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      # - id: pretty-format-json
        args: [--autofix]
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.6.0
    hooks:
      - id: ansible-lint
        entry: ansible-lint --write
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort # sort imports alphabetically and separates import into sections
