---
- name: Configure StarFit server
  hosts: all
  gather_facts: true
  become: true
  vars:
    mplconfigdir: /usr/share/httpd/mplconfig.d

  vars_prompt:
    - name: domain
      prompt: Domain name of your server
      private: false
    - name: email
      prompt: Email for registering SSL certificate
      private: false

  roles:
    - apache
    - certbot
    - starfit
    - rq
    - rqmonitor
    - mail
