#!/usr/bin/env bash
printf "Content-Type: application/json\n\n"

set -ue

files=$(find /var/www/html/data/db/ -maxdepth 1 -type f -name '*.stardb.gz' -printf '%f\n')
labels=""

if [ -f /var/www/html/data/db/labels ]; then
  labels=$(cat /var/www/html/data/db/labels | tr -s ' ' | sed 's/ = /=/g' | column -d -s '=' -J -N filename,label | jq .table)
fi

if [ -z "$labels" ]; then
  labels="[]"
fi

for f in ${files}; do
  if ! echo $labels | jq .[] | jq .filename -r | grep "$f" > /dev/null; then
    label=$(echo "$f" | sed 's/.star.el.y.stardb.gz//g')
    x="$labels"
    labels=$(echo $x | jq --arg val1 $f --arg val2 $label '. += [{"filename": $val1, "label": $val2}]')
  fi
done

echo $labels | jq
