#!/usr/bin/env python
print("Content-Type: text/html; charset=UTF-8\n")

import jinja2 as j2

# Load jinja template
jinja_env = j2.Environment(loader=j2.FileSystemLoader("templates"))
template = jinja_env.get_template("unsubscribe.html")

# Render using DB list
print(template.render())
