#!/usr/bin/env python
import header

header.http()

import jinja2 as j2

# Load jinja template
jinja_env = j2.Environment(loader=j2.FileSystemLoader("templates"))
template = jinja_env.get_template("unsubscribe.html")

# Render using DB list
print(template.render())
