---
- name: Install the latest version of Certbot
  dnf:
    name:
      - certbot
      - python3-certbot-apache
    state: latest

- name: Register certificate
  shell:
    cmd: certbot --apache -n --agree-tos --domains {{ domain }} --email {{ email }}
    creates: /etc/letsencrypt/live/{{ domain }}

- name: Test certbot renew
  shell: certbot renew --dry-run
