---
- name: Set hostname
  hostname:
    name: "{{ domain }}"
    use: systemd
  register: hostname

- name: Install sendmail
  dnf:
    name:
      - mailx
      - sendmail
    state: latest

- name: Ensure sendmail service is up
  systemd:
    state: "{{ 'restarted' if hostname.change else 'started' }}"
    name: sendmail
