---
- name: Set hostname
  hostname:
    name: "{{ domain }}"
    use: systemd

- name: Install sendmail
  dnf:
    name:
      - mailx
      - sendmail
    state: latest

- name: Ensure sendmail service is up
  systemd:
    state: started
    name: sendmail
