---
- name: Install mail tools
  dnf:
    name:
      - mailx
      - sendmail
      - sendmail-cf
      - opendkim
      - opendkim-tools
    state: latest

- name: Set hostname
  hostname:
    name: "{{ domain }}"
    use: systemd
  notify:
    - Restart sendmail

- name: Edit /etc/hosts
  lineinfile:
    path: /etc/hosts
    search_string: 127.0.0.1 {{ domain }}
    line: 127.0.0.1 {{ domain }}
  notify:
    - Restart sendmail

- name: Ensure opendkim signing mode is on
  lineinfile:
    path: /etc/opendkim.conf
    regexp: ^Mode
    line: Mode sv
  notify:
    - Restart opendkim

- name: Enable opendkim TrustedHosts file
  lineinfile:
    path: /etc/opendkim.conf
    regexp: "^InternalHosts "
    insertafter: "# InternalHosts"
    line: InternalHosts refile:/etc/opendkim/TrustedHosts
  notify:
    - Restart opendkim

- name: Add domain to be signed in opendkim
  lineinfile:
    path: /etc/opendkim.conf
    regexp: "^Domain "
    insertafter: "# Domain"
    line: Domain {{ domain }}
  notify:
    - Restart opendkim

- name: Add domain to trusted hosts in opendkim
  lineinfile:
    path: /etc/opendkim/TrustedHosts
    search_string: "{{ domain }}"
    line: "{{ domain }}"
  notify:
    - Restart opendkim

- name: Generate opendkim key
  shell:
    cmd: |
      rm -f /etc/opendkim/keys/default.* && opendkim-default-keygen
      opendkim-genkey -r -D /etc/opendkim/keys -s default -d {{ domain }}
    creates: /etc/opendkim/keys/default.private
  notify:
    - Restart opendkim

- name: Add opendkim to sendmail config
  lineinfile:
    path: /etc/mail/sendmail.mc
    search_string: INPUT_MAIL_FILTER
    line: INPUT_MAIL_FILTER(`opendkim', `S=inet:8891@localhost')
  notify:
    - Restart sendmail

- name: Flush handlers
  meta: flush_handlers

- name: Ensure opendkim service is up
  systemd:
    state: started
    name: sendmail

- name: Ensure sendmail service is up
  systemd:
    state: started
    name: sendmail

- name: Add script for listing required recordsets
  template:
    src: recordsets.j2
    dest: /usr/local/sbin/show-recordsets
    owner: root
    group: root
    mode: "0755"
