---
- name: Start redis service
  systemd:
    state: started
    name: redis
    enabled: true

- name: Create rq systemd target
  copy:
    src: rq.target
    dest: /etc/systemd/system/rq.target
  notify:
    - Restart rq.target

- name: Create rq.target.wants dir
  file:
    name: /etc/systemd/system/rq.target.wants
    state: directory
  notify:
    - Restart rq.target

- name: Create rq worker service template
  copy:
    src: rq-worker-group@.service
    dest: /etc/systemd/system/rq-worker-group@.service
    owner: root
    group: root
    mode: 0644
  register: rqservice
  notify:
    - Restart rq.target

- name: Create rq.target.wants symlinks for email workers
  file:
    state: link
    src: /etc/systemd/system/rq-worker-group@.service
    dest: /etc/systemd/system/rq.target.wants/rq-worker-email@{{ '%02d' | format(item + 1) }}.service
  loop: "{{ range(5) }}"
  notify:
    - Restart rq.target

- name: Create rq.target.wants symlinks for web workers
  file:
    state: link
    src: /etc/systemd/system/rq-worker-group@.service
    dest: /etc/systemd/system/rq.target.wants/rq-worker-web@{{ '%02d' | format(item + 1) }}.service
  loop: "{{ range(5) }}"
  notify:
    - Restart rq.target

- name: Flush handlers
  meta: flush_handlers

- name: Start rq.target services
  systemd:
    state: started
    name: rq.target
    enabled: true
