---
- name: Start redis service
  systemd:
    state: started
    name: redis
    enabled: true

- name: Create rq systemd target
  copy:
    src: rq.target
    dest: /etc/systemd/system/rq.target
  notify:
    - Restart rq.target

- name: Create rq.target.wants dir
  file:
    name: /etc/systemd/system/rq.target.wants
    state: directory
  notify:
    - Restart rq.target

- name: Create rq worker service templates
  copy:
    src: rq-worker-default@.service
    dest: /etc/systemd/system/rq-worker-{{ item }}@.service
    owner: root
    group: root
    mode: 0644
  loop:
    - email
    - web
  notify:
    - Restart rq.target

- name: Create rq.target.wants symlinks for workers
  file:
    state: link
    src: /etc/systemd/system/rq-worker-{{ item[0] }}@.service
    dest: /etc/systemd/system/rq.target.wants/rq-worker-{{ item[0] }}@{{ '%02d' | format(item[1] + 1) }}.service
  loop: "{{ ['default'] | product(range(10)) | list }}"
  notify:
    - Restart rq.target

- name: Flush handlers
  meta: flush_handlers

- name: Start rq.target services
  systemd:
    state: started
    name: rq.target
    enabled: true
